### ISSUE TITLE
task04_3.py 

### ISSUE THREAD

**Issue by kostya13** [themagoff/epam-auto#2]
https://github.com/themagoff/epam-auto/blob/16f83f23b9eb5c8874c4e8ba4de1711b59719164/task04_3.py#L7

Кодировку utf-8 можно не указывать она используется по умолчанию. Параметр кодирвоки нужен если будет что-то отличное от utf-8

**Comment by themagoff** [comment]
Без кодировки при запуске ошибка
\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u010c' in position 31692: character maps to <undefined>

**Comment by kostya13** [comment]
Тут питон проявляет зачатки искусственного интеллекта :)

Под виндой кодировка по умолчанию cp1251 в линукс utf8.
Я больше в линукс работаю, там утф8 всегда по умолчанию.
